import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Application from "./Application";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NTNU | Your groups",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Application>{children}</Application>
        <Toaster />
      </body>
    </html>
  );
}
